/*
 * Copyright (c) 2010-2014 LAAS/CNRS, WPI
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 *
 *                                               Jim Mainprice Tue 27 May 2014 
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

#include "forms.h"

extern void position_robot_at_beginning ( int ir, p3d_traj *trajPt );
extern int calc_real_dof ( void );
extern void g3d_create_robot_form ( int ir );
extern double g3d_get_qi ( int i );
extern double g3d_get_qf ( int i );
extern void g3d_add_traj ( char *name, int i, p3d_rob* rob = NULL , p3d_traj* traj = NULL );
extern void g3d_add_config_to_ui(char* name,p3d_rob* rob,double* q);
extern int draw_localpath ( p3d_rob *robotPt, p3d_localpath *localpathPt, double dmax );
extern int lpc_writepath_fct ( p3d_rob* robot, p3d_localpath* curLp );
extern void p3d_read_path ( const char *file );
extern void g3d_delete_robot_form ( int ir );
extern void FORMrobot_update ( int ir );
extern void CB_showtraj_obj(FL_OBJECT *ob, long arg);
extern void MovieDrawGraph(void);
#endif /* __CEXTRACT__ */
