/*
 * Copyright (c) 2010-2014 LAAS/CNRS, WPI
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice and this list of conditions.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice and  this list of  conditions in the  documentation and/or
 *      other materials provided with the distribution.
 *
 * THE SOFTWARE  IS PROVIDED "AS IS"  AND THE AUTHOR  DISCLAIMS ALL WARRANTIES
 * WITH  REGARD   TO  THIS  SOFTWARE  INCLUDING  ALL   IMPLIED  WARRANTIES  OF
 * MERCHANTABILITY AND  FITNESS.  IN NO EVENT  SHALL THE AUTHOR  BE LIABLE FOR
 * ANY  SPECIAL, DIRECT,  INDIRECT, OR  CONSEQUENTIAL DAMAGES  OR  ANY DAMAGES
 * WHATSOEVER  RESULTING FROM  LOSS OF  USE, DATA  OR PROFITS,  WHETHER  IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR  OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                                  
 *
 * Siméon, T., Laumond, J. P., & Lamiraux, F. (2001). 
 * Move3d: A generic platform for path planning. In in 4th Int. Symp.
 * on Assembly and Task Planning.
 *
 *                                               Jim Mainprice Tue 27 May 2014 
 */
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__

#include "forms.h"

extern void g3d_create_planner_form ( void );
extern void CB_global_search_obj(FL_OBJECT *ob, long arg);
extern void CB_specific_search_obj ( FL_OBJECT *ob, long arg );
extern void p3d_printTrajGraphContactPdbFiles(char* filePrefix, int index, p3d_rob *robotPt);
extern void CB_DMAX_param_obj ( FL_OBJECT *ob, long arg );
extern int p3d_get_user_drawnjnt ( void );
extern void p3d_set_user_drawnjnt(int jnt);
extern void CB_stop_obj ( FL_OBJECT *ob, long arg );
extern void CB_del_param_obj ( FL_OBJECT *ob, long arg );
extern void g3d_delete_planner_form ( void );
// TEMPORARY (Juan)
extern int fct_stop(void);
extern void fct_draw(void);
extern void CB_create_drawnjnt_obj(FL_OBJECT *ob, long arg);
extern void CB_print_obj(FL_OBJECT *ob, long arg);
#endif /* __CEXTRACT__ */
