#ifndef YELLOW_DEATH_XPM
#define YELLOW_DEATH_XPM
#define C_TEXT( text ) ((char*)std::string( text ).c_str())

/* XPM */
const char *yellow_death[] = {
/* columns rows colors chars-per-pixel */
"123 168 256 2 ",
(char*)"   c #010101",
(char*)".  c #0A0401",
(char*)"X  c #050902",
(char*)"o  c #0C0B01",
(char*)"O  c #02020A",
(char*)"+  c #09050B",
(char*)"@  c #050A0A",
(char*)"#  c #0B0B0C",
(char*)"$  c #120C00",
(char*)"%  c #110E0C",
(char*)"&  c #130900",
(char*)"*  c #0E1101",
(char*)"=  c #0D110C",
(char*)"-  c #061007",
(char*)";  c #141201",
(char*)":  c #1A1500",
(char*)">  c #1C1A00",
(char*)",  c #13130D",
(char*)"<  c #15190D",
(char*)"1  c #1B1B0D",
(char*)"2  c #181608",
(char*)"3  c #040312",
(char*)"4  c #0D0C13",
(char*)"5  c #090A14",
(char*)"6  c #120E14",
(char*)"7  c #110E19",
(char*)"8  c #0F1314",
(char*)"9  c #0F1319",
(char*)"0  c #141313",
(char*)"q  c #1A1613",
(char*)"w  c #151A12",
(char*)"e  c #1A1B14",
(char*)"r  c #14141A",
(char*)"t  c #1A141B",
(char*)"y  c #161919",
(char*)"u  c #1B1B1C",
(char*)"i  c #221D00",
(char*)"p  c #211C09",
(char*)"a  c #211D1A",
(char*)"s  c #1E211B",
(char*)"d  c #1D2213",
(char*)"f  c #1D2200",
(char*)"g  c #242200",
(char*)"h  c #2A2500",
(char*)"j  c #2C2A00",
(char*)"k  c #282709",
(char*)"l  c #332D00",
(char*)"z  c #322E0C",
(char*)"x  c #343300",
(char*)"c  c #3A3400",
(char*)"v  c #3C3A00",
(char*)"b  c #39390A",
(char*)"n  c #232214",
(char*)"m  c #2D2C13",
(char*)"M  c #23231C",
(char*)"N  c #2B2B1D",
(char*)"B  c #27281B",
(char*)"V  c #312E17",
(char*)"C  c #2E311D",
(char*)"Z  c #363517",
(char*)"A  c #2E3200",
(char*)"S  c #1C1D22",
(char*)"D  c #1A1521",
(char*)"F  c #201E24",
(char*)"G  c #1F2023",
(char*)"H  c #242323",
(char*)"J  c #2A2624",
(char*)"K  c #2B2B24",
(char*)"L  c #2B2C2B",
(char*)"P  c #28272A",
(char*)"I  c #2E312B",
(char*)"U  c #2C3025",
(char*)"Y  c #32322B",
(char*)"T  c #363424",
(char*)"R  c #2B2D32",
(char*)"E  c #292A33",
(char*)"W  c #2D3132",
(char*)"Q  c #2C333C",
(char*)"!  c #323436",
(char*)"~  c #312F29",
(char*)"^  c #423C00",
(char*)"/  c #473F0E",
(char*)"(  c #3F4002",
(char*)")  c #3D4025",
(char*)"_  c #444300",
(char*)"`  c #4A4500",
(char*)"'  c #4C4B00",
(char*)"]  c #474607",
(char*)"[  c #524C01",
(char*)"{  c #524F0C",
(char*)"}  c #555200",
(char*)"|  c #5A5500",
(char*)" . c #5C5B01",
(char*)".. c #575707",
(char*)"X. c #555716",
(char*)"o. c #625E01",
(char*)"O. c #655C0A",
(char*)"+. c #646402",
(char*)"@. c #6C6902",
(char*)"#. c #696708",
(char*)"$. c #726C09",
(char*)"%. c #737304",
(char*)"&. c #797708",
(char*)"*. c #686617",
(char*)"=. c #716D14",
(char*)"-. c #7A7817",
(char*)";. c #53522D",
(char*)":. c #797722",
(char*)">. c #6E6C29",
(char*)",. c #5E600D",
(char*)"<. c #706C4D",
(char*)"1. c #817D11",
(char*)"2. c #837E2C",
(char*)"3. c #7D8117",
(char*)"4. c #89890B",
(char*)"5. c #858617",
(char*)"6. c #8D9218",
(char*)"7. c #959618",
(char*)"8. c #908F1B",
(char*)"9. c #9BA01D",
(char*)"0. c #A2A41E",
(char*)"q. c #888626",
(char*)"w. c #918E2A",
(char*)"e. c #989628",
(char*)"r. c #898833",
(char*)"t. c #9C9C33",
(char*)"y. c #9B983B",
(char*)"u. c #908F2D",
(char*)"i. c #A29D38",
(char*)"p. c #A29C24",
(char*)"a. c #9EA32E",
(char*)"s. c #A8A829",
(char*)"d. c #B7B72C",
(char*)"f. c #ACAA34",
(char*)"g. c #A7A638",
(char*)"h. c #B1AD3A",
(char*)"j. c #B9BA39",
(char*)"k. c #ACB035",
(char*)"l. c #C1BD3A",
(char*)"z. c #BEC036",
(char*)"x. c #EEF405",
(char*)"c. c #F4F501",
(char*)"v. c #FAF601",
(char*)"b. c #F5FA02",
(char*)"n. c #FFFF01",
(char*)"m. c #F4F50C",
(char*)"M. c #F5FB0C",
(char*)"N. c #FEFE0B",
(char*)"B. c #FAF70B",
(char*)"V. c #EFF717",
(char*)"C. c #F6FA14",
(char*)"Z. c #FDFE13",
(char*)"A. c #F3F51C",
(char*)"S. c #F6FC1A",
(char*)"D. c #FCFE1B",
(char*)"F. c #F6F612",
(char*)"G. c #EDEE0C",
(char*)"H. c #C5C639",
(char*)"J. c #CFD13C",
(char*)"K. c #F3F523",
(char*)"L. c #F5FA23",
(char*)"P. c #FCFE23",
(char*)"I. c #F4F52C",
(char*)"U. c #F5FB2B",
(char*)"Y. c #FCFE2C",
(char*)"T. c #FAF628",
(char*)"R. c #ECED3A",
(char*)"E. c #ECF239",
(char*)"W. c #F2F534",
(char*)"Q. c #F6FB34",
(char*)"!. c #FCFD33",
(char*)"~. c #F4F53B",
(char*)"^. c #F5FB3B",
(char*)"/. c #FBFD3B",
(char*)"(. c #F9F639",
(char*)"). c #EEF02C",
(char*)"_. c #9C9A4F",
(char*)"`. c #A29E4C",
(char*)"'. c #A8A745",
(char*)"]. c #B3AD47",
(char*)"[. c #BBBB43",
(char*)"{. c #B6B449",
(char*)"}. c #BBB855",
(char*)"|. c #AFA954",
(char*)" X c #B3B366",
(char*)".X c #C1BB51",
(char*)"XX c #BEC245",
(char*)"oX c #BEC168",
(char*)"OX c #CDCB4C",
(char*)"+X c #C8C847",
(char*)"@X c #D1CF48",
(char*)"#X c #D9D949",
(char*)"$X c #C8C757",
(char*)"%X c #D1CE57",
(char*)"&X c #D5D554",
(char*)"*X c #DBDC54",
(char*)"=X c #D9D75B",
(char*)"-X c #CCD251",
(char*)";X c #E1DE58",
(char*)":X c #DEE258",
(char*)">X c #DFE447",
(char*)",X c #E3E34C",
(char*)"<X c #E8EB48",
(char*)"1X c #F1EE4B",
(char*)"2X c #EEF24B",
(char*)"3X c #EEF445",
(char*)"4X c #F3F444",
(char*)"5X c #F5FA44",
(char*)"6X c #FBFD43",
(char*)"7X c #F4F44B",
(char*)"8X c #F9F74B",
(char*)"9X c #F5FA4C",
(char*)"0X c #FCFD4B",
(char*)"qX c #F9F443",
(char*)"wX c #E4E654",
(char*)"eX c #EBEC53",
(char*)"rX c #ECEB5A",
(char*)"tX c #E7E659",
(char*)"yX c #F3EF51",
(char*)"uX c #EDF255",
(char*)"iX c #EEF25B",
(char*)"pX c #EEF95F",
(char*)"aX c #F4F553",
(char*)"sX c #F9F654",
(char*)"dX c #F6FA53",
(char*)"fX c #FBFC53",
(char*)"gX c #F4F45B",
(char*)"hX c #F9F65C",
(char*)"jX c #F5FA5C",
(char*)"kX c #FBFB5B",
(char*)"lX c #D0CE62",
(char*)"zX c #DBDA62",
(char*)"xX c #D7D665",
(char*)"cX c #D9D774",
(char*)"vX c #CBCA69",
(char*)"bX c #E3DE63",
(char*)"nX c #E1DE7B",
(char*)"mX c #DCE365",
(char*)"MX c #ECED64",
(char*)"NX c #E7E668",
(char*)"BX c #F3EE63",
(char*)"VX c #EEF263",
(char*)"CX c #EEF569",
(char*)"ZX c #F4F563",
(char*)"AX c #FCFC63",
(char*)"SX c #F4F46C",
(char*)"DX c #FAFC6C",
(char*)"FX c #F6F966",
(char*)"GX c #E9E875",
(char*)"HX c #F5F577",
(char*)"JX c #EFEF79",
(char*)"KX c #BEBF83",
(char*)"LX c #D2D18F",
(char*)"PX c #EAED86",
(char*)"IX c #F5F385",
(char*)"UX c #EEF181",
/* pixels */
"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.B.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.N.N.N.n.n.n.n.n.b.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.N.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.N.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.n.N.n.n.n.n.n.n.n.n.v.n.n.b.n.N.N.n.N.n.v.n.n.v.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.N.n.n.n.n.n.n.n.n.n.n.n.n.N.M.Z.Z.Z.Z.C.Z.D.D.S.P.P.D.D.P.D.Z.D.D.C.m.D.Z.Z.N.N.n.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.M.b.n.n.n.N.M.N.D.D.P.T.L.Y.!./.6X0X0XsXfX8X6X6X^./.!./.!.Y.P.D.D.Z.N.N.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.Z.N.N.D.D.P.U.Q.Q.6X9XaXeXz.d.7.4.&.&.&.&.&.1.4.4.6.0.H.#XZXsX8X/.!.Y.D.D.N.M.N.N.N.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.N.n.b.D.P.!.qX9XpXwXj.3.| c g > i : : : $ $ ; ; ; ; : : : > i l ` 1.h.#X2X4X6XP.S.Z.N.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.N.b.n.c.Z.P.).qXAX;Xu. .j ; : o   .     .                   . .   . o $ ; : j | 6.@X7X0XI.A.D.N.b.n.N.N.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.c.N.N.m.T.~.eX$XO.h : X X X .                                             . o $ ; g | g.BX0XY.D.m.N.v.n.n.v.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.N.v.N.N.x.V.^.<Xl.o.: & .   O +                       O O O                       .     . $ : ` f.eX5XY.m.Z.N.N.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.C.!.jX&X+.$ . .   . O   O   O                   O O 3 O O                         . .   . $ O.$XkX(.F.b.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.N.B.D.L.0XeXe.g   .   X             O                   O   O O O                   + X       X + o . i 1.rX0XP.Z.Z.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.c.D.!.1XbXo.. & .                     O   O   O                                           . X       . . i [ =XsXW.D.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.P.I.hX=Xc . .     O O                   O                                     O     O X     X X O o . . & & l .XsX(.D.B.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.N.n.n.n.D.I.hX}.h .           O O                                                           O       X X   X   X X . . ; > g.aX!.F.Z.v.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.N.N.n.v.N.L.dX[.h                 O                                                                 .   X X X X . X X o . o f f.fXQ.D.N.n.n.n.n.n.n.n.b.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.N.N.v.n.n.n.n.Z.Y.0Xl.l . .                                                                             X . O O O @ O X X X o X = . : g k.sXY.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.v.n.n.D.qX@Xl .   .                                                                     O   X   O X   @ 5 5 X X * o o * . ; o $ h @XQ.D.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.N.b.n.n.N.m.Y.BX^ & .                                                                           O . O . O X + 5 + @ . o X - o o X 0 & : _ ,XQ.D.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.N.N.P.fX1.: . .     X                                                                   X     X X + @ + # # @ @ # # # - X w 5 6 ; : %.dX!.D.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.n.b.D.6Xl.: . .     O                                                                         O X @ + + o o @ 4 4 7 4 4 = = 8 5 # 1 : ; [.8XP.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.N.n.b.N.Y.,X| . O     O   O                                                               . O O . X O + o # @ o @ 5 7 5 4 # , 8 4 9 0 o : : v ZX(.D.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.D.5Xh.;             O O       O O                                                       X O . X + o @ o # o 4 7 6 % = = 8 9 9 8 < ; > ; p.8X!.B.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.M.Y.jX{ .             O           O                                                   X O O X o @ @ # # # % # 7 7 7 , , , 8 9 9 8 , < < > ` eX!.D.N.n.n.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.B.D./.OX$                       O O O                                                 .   O + o + @ # # # # = % 7 7 7 6 , , 8 8 r 9 q < w > : [.4XL.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.P.9X-.. O                     O O O                                                 O X + X + # @ # # = # = = 6 7 t 0 q 2 < w y y y u e k i @.dXU.Z.n.n.n.n.b.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.B.!.eXA X O                     O O                                               X O . + o + @ # # # # # , , = 6 r t D t q < < e u u u e p i g rX!.Z.v.n.N.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.Z.F./.+X;                                                                             O X + . o @ # # # % 6 = = , 6 r 7 t t t 1 w u s u u u a p : j.0XD.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.P.0X6.;                                 O                                         . O X o @ + @ # # # , 8 # 0 8 6 0 t a D t u y u a u u a a M > &.5XP.n.N.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.B.Y.dX .X X                                                                         O X O @ @ # # # # 0 4 % 0 0 r 0 q t t F t S u u u M u F a a > | sXP.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.Y.aXv o                     O O                                               X O + + # 4 # 4 # % % 6 % % 0 r t q w y y S S S G s s M a F F M j h MX/.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.T.eXh .                         O                             O             .   . + + + + # # # 6 % % , 0 6 q q y 1 e y S S G s s s M J J F a k i bX/.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.N.L.,X:                                                                         X O o 5 + + 4 % % % % , , 6 q q 1 1 d e u F F G G n M B H F J B k i +X/.Z.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.Y.#X$                                                                   O O X   @ + + 4 4 # # % , % 6 q t t q w e e u s F F G s B M M J P P J z i [.6XZ.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Y.J.;     O     O   O                         O O O   O         O         O     X 4 4 5 # 4 # # 0 , 0 t t D t t u u F F F F H H M B B J E P J z i f.6XD.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.n.n.Z.P.H.$ .   O             O               O O O O O   O                 O O + X X @ @ # 4 4 # % , % 0 r y D D S S S S F F F J H B B N J J E P J m h g./.Z.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.Y.d.$         .     O   O             O O O O O                   O O   O   . O + @ # # = # = , 0 , 8 y y y S S S S F F F J F J N B K L E L L m i s.(.Z.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.Z.!.d.: .   O           O O                                             O O O + + @ # # # o # , , , w w w y d S S S H a J J J J J L J L L L L ~ m h g.qXD.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.T.H.:   O                             X       .                       O O O + # @ + o = = = = = w 8 < w d < y G w B H u H J P P L L E L L U ~ m i h.(.D.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.N.Y.J.:                                                                     + 3   + q o # o o 0 = w w 8 < d d s d M M M M M B P E E R R L I U ~ z l h.(.D.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Y.>X>                         X   O                 O O O O O           O . # + . @ . q 0 0 4 8 8 = X         y # F H K W K L L R R R W I I T z h .X(.D.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Y.eXi                       O         . . . . . . . O + O O           . .     # o o # 4 # , 0 o       X     .   . + t G H H L L R R R W I I T b i OX(.D.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.Y.eXj .                       O O . . & . : h c h & $     .             X . X - o # 8 + , %   . . ; j l i p & & . .   F J P U I I R R R ! Y U b i NX!.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.P.2X_ .                         .   i >.}.GXHXIXJXcX`.{ >   .   O O O O X X o X @ 4 4 , 2   . ..`.lXJXIXJXGX.X2.i . . . q L L U I I ! Y Y Y C b x MX!.B.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.P.aX>.                        & . ^ xXMXsX4XW.0X(.4XkXFXg.> .   3 3 3 O X X X - @ 8 4 q . i `.*XAX5X(./././.0XgX%X[ & . + J L L R Y Y ~ Y T Z j ' SX!.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.P.dX3.o   X           O     &   j GXrX^.!.S.D.Z.Z.D.A.6XFXg.o . O 3 3 O   X   - O 4 4 ; . y.VX0XY.S.D.N.B.Z.D.(.sXNXc .   F L L Y L Y Y T T Z k #.ZXY.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.D.qX'.; X             O     . . g.fXQ.S.M.N.N.n.N.N.N.D.(.ZX| . .   3 O @ O 5 @ X - # ; ' VX5XP.Z.N.n.n.N.N.Z.S.!.sX.X& . % ~ N T U ! ! Y T T g 6.9XS.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.D.6X-Xg   X               . . c #X!.D.N.N.n.n.n.n.n.n.N.P.8X].> .   O O @ @ @ @ o - , > t.9XU.Z.N.n.n.n.n.n.n.N.P.6XbX/ . % N T U I Q W Y T Z : +X/.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.N.N.n.Z.Y.VX_ X           O     o O *.kXL.N.n.N.M.N.n.n.n.n.N.D.(.JXj . X       . X X - o ; f :X6XS.N.N.N.N.n.n.n.n.M.Z.Y.kX5.. & I L W Q Q ! ) C Z l eX!.Z.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.A.9X6.X X               $ & u.fXS.M.n.n.n.N.M.N.N.n.N.Z.(.HXA . .   . X X o o * o ; j #XY.D.n.Z.N.n.n.n.n.n.n.M.D.0Xs.. % W P Q Q W I C Z i 1.7XU.N.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.N.n.Z.U.#X> o               o $ |.1XP.N.n.n.n.b.b.N.n.n.n.D.^.JXc . . X   o   X o % # : l #XY.Z.N.B.N.N.n.n.n.n.n.n.D.^.z.o o E R Q E Q U C ( i @XqXP.N.n.N.v.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.n.B.S.0X-..               o . |.4XD.Z.v.n.v.n.n.n.n.n.n.Z.^.JXc     +   . . X X % + & l eXT.Z.n.N.N.n.n.n.n.n.v.M.D.!.H.$   G W Q W W I ) * $.yX!.Z.v.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.N.n.n.N.Q.NXc .             o . |.fXP.Z.v.N.n.n.n.n.n.n.M.Z.^.JXj .         o X o 4 5 : i #X!.Z.n.n.N.n.n.n.n.N.n.b.P.6XH.$ . W L W W N C A f &X~.S.N.n.v.v.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.b.S.sX].$ .           $ . `.8XP.F.Z.n.n.n.n.n.n.n.n.D.5XnX> .     # O + - - + # 2 i l.0XZ.n.n.v.n.n.n.n.n.N.N.P.0Xj.& % I L L I I Z f t.fXY.Z.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.B.n.n.n.Z.(.SX*.  .   @     . . q.3XP.N.n.N.n.n.v.n.n.n.Z.P.dX{.$ .       + + - @ 5 o o : e.fXD.n.n.n.n.n.v.N.N.N.N.T.kXe.: $ L L L Y N i | VX(.D.N.n.n.n.N.N.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.N.T.8X%Xf .         . o o.2XY.D.n.N.v.n.n.N.v.N.D.(.ZX*.. X   X @ @ @ @ X - @ * >  .FX!.Z.N.n.n.N.n.N.N.Z.Z.!.aX-.. a M Y ~ N Z i XX8XP.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.N.Z.Y.jXq..           . g :X5XV.M.c.N.b.n.n.N.F.!.sX%Xg   X   X X   + X X - X * > : }.yX!.B.N.n.c.n.n.b.Z.S.qXGXh $ B N K K z i $.AXY.D.N.n.n.n.n.B.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.).:Xh .         X ; q.pX/.P.S.C.D.Z.B.D.W.sXHX} X     X       @ X - - X o , ; { NX7X/.D.m.Z.N.Z.Z.Y./.FXy.o k a N B V z : %X6XD.N.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.b.n.n.n.Z.Y.dX=..         O   f '.pX5X5X^.!.U.Q.6XjXGX*.$       X O X o @ O X # @ = = 1 $ } zXAX4X/.L.L.K./.~.iX$Xh > U U B B V h  .hXY.Z.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.N.n.n.n.n.n.n.n.n.Z.^.}.: .         . . > #.XX:XCXVXVXZX:Xi.v $         X   O .   X O @ 4 X # 4 ; : v u.&XrXkXkXkXeX+X-.g > M w U m m k ; f.qXP.N.n.n.n.n.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.n.n.n.n.n.n.b./.GXc .         X   . f > v ' ....v g o . . .   X X           . O # # o o o w : : i l c [ o.[ ` l i g B H I s C n d g *X!.D.b.N.n.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.N.N.n.n.n.n.n.n.N.L.ZX| . .                 X .   X o .             X   @   . > . . 4   * o = X = * ; ; g g : h i i k a M u G s s d n v uXP.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.P.0X5..                                         X X   + . { LX;.  . X = = @ 8 4 , 2 : : > > < > 1 k d n u H G H d h +.3XC.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.!.0..       O             O             O   X     *   p vXUXcX> o o   5 8 @ 4 4 6 , ; 2 < < 1 1 e 1 u M G H H n > 3.^.N.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.!.H.$                                 O O     X . . $ w.FXsXDXt.o   X # X * # 6 , % ; , w y w < e y u S S u u k : g./.N.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.!.*X:               O       O       O 3 O O       . o.ZX/.I.4XZX=.o . . * o # % 6 6 0 , 0 0 w w y y S S S u < k > {.6XZ.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.D.W.eXi                       O O       O O O   o . ` wX~.P.D.D.(.NX| &   * # # 4 7 4 8 0 0 r y y D S u u u 1 1 g i %X0XD.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.D.T.aXc               O                     O +   v =X4XP.N.b.Z.P.8XGXv . . . # 4 4 r 4 7 4 r 9 9 9 y t u e q 1 f h GX^.Z.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.P.dX...             O O                     . . ].jX!.Z.N.N.v.D.Y.7X%X$ . o # @ = # 8 4 0 4 9 9 9 0 y y q p p i _ HX/.D.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.D.8X$.o             O                       . ] SX9XP.c.N.n.N.B.P.(.MX*.  = o @ - @ 4 4 , = 8 8 < 2 q q a p i i o.gXY.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.!.d.h o X         O     X               . $ >.HX9XY.D.m.N.D.D.P.W.CXr.  @ @ @ - - - - 2 * 8 - < 2 ; , p & & : s.0Xm.N.v.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.b.D.0Xj.@.o X X       O         O       X   $ X.GXDX7X/.!.Y.!.!.^.fXJX*.o + O 8 - - X X X * o 1 * * > : . i o.H.0XL.Z.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.N.B.P.0XuX*X-.j X O     X   O O     O     o . $ r.cXHXHXZXtXwXFXSXxXr.;   3 5 3 @ - @ o # q * o * : & i &.J.7X6XK.P.Z.v.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.M.P.U.6XuX:Xu.A X .   . O O   +   O     . . % l ^ ` [ ` ` [ ` x : + o + 9 3 @ @ X , , . ; ; . h :.=XkX(.Y.D.D.Z.b.b.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.v.D.T.!.(.9X>Xw.x . . . .     O O       . . . $ $ o o $ o $ . . .   + O   = X   o $ . . h q.=XhX/.T.D.D.B.b.n.N.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.Z.Z.S.L.W.sXNX`.] . . .       O   @     + O             . % . .   X = X   ; * . v _.mXDX5X!.D.B.n.N.N.n.n.c.v.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.b.n.n.v.n.N.Z.B.Z.P.K.6XAXbX{.v .       -       +       X     O .       + + @   ; * X ( t.NXVX9XU.S.Z.N.v.N.c.N.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.n.n.v.n.n.Z.N.Z.Y.6XhXSXSXIX_.* .                           . o   % O O   % O = 3.UXSXFXdX9X!.D.b.n.n.n.N.B.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.N.n.n.v.n.N.D.Y.<Xs.e.cXCXSXJX-.X           O O               X     O 5 O . & O.GXHXCX:Xa.9.<X^.D.n.n.n.v.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.S.Q.+.i > x XXFXFXGX>   +       O O O     .           O O   . $ i lXSXFXmXA < A } <XP.M.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.P.kXc . ; ; } GXFXCX'             O             @             X ( HXZXCX*.* * ; A tX/.Z.N.N.N.n.n.N.n.n.b.n.n.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.T.sX` o   . f lXVXVXt.- .                   +         X X . * * 3.CXVX-Xf ; . . v rX(.P.Z.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.N.n.N.N.n.n.n.n.n.n.n.n.N.N.n.n.n.n.n.v.n.b.P.dXr..   . o -.VX3XVX%.i $ o . . . .       .     . X X . * f ..tXpXCX3..     * @.AXQ.D.Z.v.n.n.n.n.b.n.n.n.n.n.n.n.N.n.n.n.N.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.n.N.n.n.n.n.n.n.n.n.n.b.N.N.N.N.n.n.n.n.n.N.D.0X}.  .   & : XXjXuXVXOXi.$.| ^ h i i i i : i h l v ' -.t.+XDXdXVXxXA . . . . f.9XL.Z.N.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.N.N.N.n.n.n.n.n.Z.Q.mXf X   . i  .HXjX7X0X(./.qX8XsXaXeXwXwXtXtXeX1X4X4X7XfX^.5X9XCX>.*   $ & $ wXQ.S.n.v.n.n.n.n.n.N.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.N.n.n.n.M.S.jX .    + . ; u.DXdXI.P.P.D.D.T.P.P.(.!.!.T.Y.P.D.P.Y.Y.Q.W.FX'.. . .   o v uXY.C.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.v.n.N.n.n.n.n.n.n.n.n.n.n.n.M.D.5X6.X X   . o > {.SX8X!.P.Z.Z.Z.Z.Z.D.D.Z.Z.Z.D.D.P.Y.(.0XgX$X> . .     . 2.gXU.m.n.b.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.N.n.n.N.n.v.n.n.N.N.n.N.n.n.n.n.n.n.n.n.v.Z.b.m.^.-Xo       o $ : `.SXaX(.!.!.Y.P.D.P.P.Z.P.Y.T.(.qX0XkXBXh.f . o     X $ {.sXL.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.N.N.n.v.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.v.D.L.,Xj $       o : . } '.bXMXZXkXdX8X/././.qX8XhXDXHXxX{...* .       X o i bXqXP.Z.n.N.n.n.n.n.n.n.n.n.n.n.n.N.N.n.v.n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.N.n.n.N.N.b.N.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.M.S.E.$.. X X       . * : x ^ | $.-.4.7.7.7.6.1.@.| ^ h : o   .         ; o.hX!.D.Z.v.n.N.n.n.n.n.n.n.n.n.n.b.n.n.n.n.N.N.b.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.Z.Z.D.D.S.D.N.N.n.b.n.N.N.B.n.n.n.n.n.n.n.n.n.N.C.!.#X .X X           X o ; ; f i i i i i : > > g i $       @       ; ^ J./.D.B.n.n.n.n.n.n.n.n.n.n.n.n.v.n.N.N.Z.D.D.D.D.Z.m.M.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.S.T.!./.6XqX~./.Y.P.Z.N.N.n.N.N.n.n.n.n.n.N.n.n.v.n.N.S.6XrXu.;       O           .       . .     X .       O     . . ; 2.NX0XS.Z.n.n.n.n.v.N.n.n.n.n.n.n.n.N.N.Z.P.!.!.5X6XqX(.!.T.Z.N.N.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.F.T.6X8XtX%X].i.{.%XBX8XI.A.Z.N.N.B.n.n.n.n.N.N.n.n.N.N.n.N.Z.Y.9XOXl   o     X                               +     o . j f.eX0XD.m.N.N.n.n.v.n.N.N.n.n.n.n.n.n.Z.D.T.8XeXOXh.i..X%XBXfX/.L.Z.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Z.(.R.d.o.h i i & : $ v e.wX0XT.Z.N.n.n.n.n.n.N.N.n.n.N.n.N.n.v.Z.L.R.zXv . .   X   X                                 . j +XkX/.T.N.N.n.n.n.n.n.n.n.N.n.n.N.N.N.Z.T.0XJ.1.l : : i i i ^ &.l.1X!.S.N.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.N.n.n.n.n.N.n.n.N.n.N.N.Y.iX+.; *   . . . $ ; $ & ^ -XdXU.Z.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.B.Y.1XzXl .     O   X       O O               O   . h $X1XW.P.Z.N.n.n.n.n.n.n.n.n.n.n.n.n.Z.D.T.sXf.v   ; g : > o . $ $ > w.jXW.D.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.N.n.n.Z.P.6X%.f X               . . g c +X9XT.Z.B.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Z.Y.aX{.:   O       X X       O       X         o g.gX6XD.N.M.N.N.n.n.n.n.n.n.n.N.n.v.Z.F.!.fX6.A . ; .           .   . ; g.jXP.M.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.v.n.n.n.n.n.n.Z.(.@Xg     O O O           O . > A =X0XP.Z.n.n.n.v.n.n.n.n.n.n.n.n.n.v.N.D.Y.gX+.:     O                   O O O   . . } rX^.G.Z.n.n.n.n.n.N.n.n.n.n.n.n.n.n.Z.Y.sXs.j o                     . . _ VX!.Z.n.n.n.n.n.n.n.n.n.",
(char*)"N.n.N.n.n.n.n.n.n.n.n.v.n.S.0Xp.* .     O O O     O +   ; . X } yXT.D.v.n.n.v.n.n.n.n.n.n.n.n.n.n.N.b.Z.Q.wXx ; .     .           .     O     . v &X5XT.N.c.n.n.n.n.n.n.n.n.n.n.n.v.n.N.D.0X&Xl . *     .     @     .   . : $ &X!.Z.N.n.N.n.n.n.n.n.n.",
(char*)"N.N.n.n.n.n.n.n.n.n.n.n.n.P.0X%.                O   O O   o . . p.0XD.n.n.n.n.N.N.n.n.n.n.n.n.N.N.N.N.b.S.!.wX .> .         .         +   . : ` *X2XY.m.n.n.n.n.n.n.n.n.n.n.n.n.N.N.n.N.Y.aX$.& . O O         O           . - k.qXZ.N.n.N.n.n.n.n.n.n.",
(char*)"n.N.n.n.n.n.n.n.N.v.n.n.n.D.8X+..             X   4     +   % . ^ DXI.D.N.n.v.N.N.n.n.n.n.n.n.n.N.M.n.M.M.S.6X<Xe._ o . &     . o . . . . l w.MX7X!.D.M.N.v.c.n.n.n.n.n.n.n.n.n.n.N.n.S.0X@Xi . & O O O     @ O + O     O   * e.6XZ.N.n.n.n.N.n.n.n.b.",
(char*)"n.n.n.n.n.n.n.n.N.n.N.b.n.D.^.%..                 O         . . ; [.7XY.N.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.M.S.U.^.<Xf.O.h i > ; ; : h  .f.eX8XQ.P.m.n.b.b.N.n.n.n.n.n.n.n.N.N.n.n.n.Z.Y.dXq.$   +           O O     O O   . - k./.Z.n.n.n.n.v.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.N.N.n.n.D./.7.. .               O           . . *.SX5XL.C.D.Z.N.n.n.n.n.n.n.n.n.n.n.n.v.N.n.b.Z.Y.4XhXHXxXj.XX[.zXMXhX8X!.S.Z.N.n.n.n.b.n.N.n.n.v.n.n.n.N.N.N.N.Z.P.4XHXl o O                         + . < XX/.Z.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.N.N.v.M.D.^.OX:                 O               g vXCXdX/.!.S.N.n.N.n.n.n.n.n.n.n.n.n.n.v.n.N.n.Z.P.!./.6X6X^.6X/.!.Y.P.Z.N.n.n.n.n.n.n.n.n.N.n.N.n.n.N.N.B.D.P.(.dXJX XX   O                       O O   v mX^.C.b.n.v.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.v.v.N.Z.F.U.3XJXf                       O         X f ..k.:XyX0XY.D.Z.N.Z.Z.n.n.n.n.v.v.n.N.n.v.n.n.Z.Z.Z.D.D.C.Z.C.Z.N.N.n.n.n.v.n.n.n.N.n.v.N.N.B.Z.Z.F.P.!.I.7X*Xg._ *   X                         O + . { UX9XU.M.b.n.n.N.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.N.n.n.M.Y.E.SXoX>     O                         X d   * ; c 2.&XjX6XY.P.P.Z.b.N.n.n.n.N.N.v.B.Z.N.n.n.n.N.N.N.N.M.b.n.N.n.N.N.n.n.n.n.n.n.b.n.N.N.D.Y.(.!.0X<Xj.#.l $   o < X X                       O     X.LXZX0XL.x.N.v.n.N.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.S.6XCX-.> o     O O                           * 2   . : h  .d.eX7XqX!.D.M.B.Z.n.n.n.N.N.v.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Z.Z.P.T.qXhX,X7.} h & & % 6 o                       X       @     f w.pX^.P.M.n.n.v.n.n.N.",
(char*)"n.n.N.n.n.n.n.n.n.c.D.W.wX| ; .                                 0       . $ $ > $ > _ q.&XuXQ.Y.Y.P.Z.n.n.n.n.N.n.n.n.n.n.n.n.N.N.Z.n.n.n.n.n.n.b.n.N.M.Z.P.Y.W.0XaX+X$.v f ; $ , 4     X   O                                 . f -.jXQ.D.n.n.n.n.n.n.",
(char*)"n.n.n.N.n.n.n.n.b.Z.L.1X1.$ $                                                   ; : : ; v @.d.aXdX^.P.D.D.N.M.c.n.n.v.n.n.n.n.n.N.N.n.n.v.n.n.N.N.N.D.P.I./.aXrX7. .A f o . X   O 3 O     .   O                                 . ; s.9XY.M.n.N.n.n.n.",
(char*)"n.n.Z.N.n.n.n.n.n.Z.6XH.: .         O   O     O                       +   O O       X ; : ; i ^ e.@XfX/.K.P.P.Z.N.n.n.n.n.n.n.n.n.n.n.n.n.n.N.D.P.A.I.6XdXOX1.c h : o *                       O         O O                       . h iX!.M.n.n.n.n.n.",
(char*)"n.n.N.N.n.n.n.n.n.P.8X&..                   O O                       O O O O           . . & & : l %.H.jX0XW.Y.L.Z.n.n.n.n.N.n.v.n.n.n.n.Z.D.!.^.fXgXj. .h : & . . .         O             . .                     X         O 3 . : s.).D.M.n.n.n.n.",
(char*)"B.N.n.n.n.n.n.n.n.S.kX} . .               O         O .                 O           O       o o o $ o > ,.{.VX9X!.P.Z.N.N.N.N.n.N.n.N.B.Z.L.I.fXZXt.^ : o O . .           O O O   O                               O O O         3   $ 4.~.P.b.N.n.N.n.",
(char*)"N.N.n.n.n.N.n.v.n.D.7X@.. .           X             X x ; :   .         O           O O         . X o X X X ..g.tX4X/.T.D.B.Z.N.N.G.D.!.~.kXwX8.j : .                   O     + O             X . : g m   .     +   O   O       O . ; 0.6XC.Z.b.N.n.n.",
(char*)"n.n.n.n.n.B.n.n.v.D.^.d.: .   +             + O . o $.mXNXj.-.x $ . . .     .             O X         X X X . . v `.NX1XI.P.D.C.S.!.0XhXzX-.g $ . . .             O                     . . > _ 6.d.GXcX_ $         .           o o h ,X!.D.b.n.n.N.n.",
(char*)"n.n.n.n.n.n.n.n.n.N.P.9X8.$ &           .   . . $ u.uX5XE.4XdXMXvX:.j : $   .   .       O       O O       X o o . . ^ e.,X7X^.5X8XhXOX$.i . $ .     O       X     O       X   X . . & : _ r.$XMX0XW.0XgXGX .o $               . . g d.9XT.Z.n.n.n.n.n.",
(char*)"n.n.n.n.v.n.n.n.n.N.Z.U.2Xf.j $ .     .   . & l {.uX^.P.S.P.A.!.^.7XuXj.#.l $ .                               o & . . . h q.cXIXvX*.i . & .         O O O O       O           . & c -.OXFXsX5X/.L.P.S.!./.gX8.i $ . & +   .   . ` z.9XI.D.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.b.N.Z.Y.7X-X=.g * X . & l 5.*XkX!.A.Z.b.b.N.M.D.P.Y./.aX;Xe.^ $ .   O                     X     $ % .   . > ] : o                           X   o     $   ; } {.*XjX6X!.Y.D.m.Z.B.N.N.C.K.3X@X| i . & $ ; _ 5.wXfX/.A.b.n.n.n.n.n.n.",
(char*)"n.n.N.n.n.n.n.v.N.N.b.N.M.Y.0XgXuXz.s.k.OX<X~.!.S.N.N.m.Z.N.N.n.N.b.B.S.!./.4XeXj.#.; X         O     O O     X   o     0 =     .       O           O O O O         X . > -.&XaX4X!.Y.D.Z.Z.N.N.B.Z.N.c.Z.D.Y./.kXrX+X0.s.J.uXfX^.Y.S.N.n.n.n.n.n.n.n.",
(char*)"n.n.N.n.n.n.N.n.Z.N.n.n.v.N.S.Y.U.!.Q.Q.I.Y.D.b.n.n.n.n.B.n.N.n.n.n.N.n.N.D.P.Y.6XgX+X=.h . .   .     O               O   X *               O                     * c q.:XdX^.Y.D.N.b.n.n.n.n.n.N.v.N.n.n.b.B.D.P.Y.!.!.Q.Y.P.S.P.C.M.n.n.n.n.n.n.n.n.",
(char*)"N.n.n.n.n.n.n.n.N.N.n.n.n.n.N.Z.Z.S.D.S.Z.Z.n.n.n.n.n.N.N.n.n.n.N.n.n.n.N.N.Z.D.L.!.5XgXbXq.h & . . O                                   O             .   . . : ^ s.MXdX^.Y.D.M.N.b.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Z.D.D.D.D.Z.Z.Z.N.b.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.N.N.n.n.n.n.n.n.n.N.n.N.b.n.n.n.n.n.n.N.n.n.v.n.n.n.n.n.n.n.N.Z.N.Z.P.K.R.AXbXy.c . .         X                                 . o     & : ^ ].tX0X(.U.S.N.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.N.N.N.n.N.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.b.Z.P.I.W.kXbX'.( @ .           O O O               O O O       $ & [ XXZX9X!.P.D.Z.N.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.N.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.N.v.n.n.n.n.n.N.n.n.n.n.n.n.N.N.N.n.n.n.n.N.n.n.N.n.n.n.n.n.v.N.Z.P.Q.4XCXPX XZ     X   O O O O O               O O O O   ;.LXPXtX^.U.m.b.N.N.n.N.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.N.n.n.n.n.n.n.n.n.v.n.N.v.b.D.L.dXMXPXKX)   @             O         O               <.LXPXFX^.L.Z.N.N.n.n.n.N.v.n.n.N.N.N.n.M.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.b.n.n.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.b.n.n.n.n.n.N.n.N.N.b.c.N.D.T./.uXmX*.$ .                 O     O               +     g r.JXuXQ.A.Z.N.N.v.n.n.n.n.N.v.N.N.n.n.n.N.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.N.N.n.n.n.n.M.n.B.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.N.D.Y.6XsXNXu.i   .   O   X         O               X         %   . . x '.SXqX!.P.F.N.n.v.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.n.n.n.n.n.b.n.",
(char*)"n.n.n.n.b.n.n.n.n.N.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.D.!.8XSXg.v . . .   O O                                         .   . . o } OXyX0X(.D.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.n.N.N.n.v.n.N.n.n.n.n.n.n.n.n.v.n.n.n.n.N.N.n.N.Z.P./.ZX$X..* X   .               O               O       O               % . & ; :.zXAXQ.S.M.n.n.n.n.n.N.n.N.n.n.n.n.n.n.n.n.n.N.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.N.N.n.N.N.n.v.N.N.N.n.n.n.n.N.n.n.v.n.n.b.n.n.n.N.B.B.P.!.R.tX5.; X                   O   O     . . ; j *     X           X     +   + .     j e.eX5XY.D.Z.n.v.N.v.v.N.v.n.n.n.n.n.n.v.n.v.n.N.n.n.n.N.n.n.n.n.n.n.n.N.n.n.n.n.",
(char*)"n.n.n.n.n.N.n.n.n.n.n.n.n.v.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.v.n.D.T.0XFXh.x . X   ;     O                 . . ; ,.{.NXg._ o .     +   O     O     +     o . . } XX7X/.S.Z.b.n.n.N.b.N.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.N.N.n.v.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.v.n.n.n.n.n.n.n.n.n.N.n.n.b.N.N.N.M.n.n.n.n.n.n.v.N.b.Z.P.!.7X&X| $ o o         O   O O +       .   $ ..$XDXdX3XjXFXg.` ; .     O                 .   & . : -.rX9XL.D.C.b.n.v.n.n.n.b.n.n.N.N.b.v.b.N.N.N.v.n.n.n.n.n.n.n.n.N.n.N.n.n.",
(char*)"n.n.n.N.n.n.n.n.n.n.N.n.n.n.n.b.b.N.Z.Z.D.D.D.D.D.D.N.Z.N.n.v.n.N.N.P.T.dXMXq.g   X     .   . .   O O       . . & | [.hX6XQ.Y.Y.W.(.fXyXe.v o .   q     X X   O   . o     . o x k.iX^.U.D.v.N.n.n.n.n.N.N.Z.D.P.P.D.S.F.Z.M.M.n.n.n.n.n.n.n.n.N.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.N.b.n.n.b.B.Z.S.L.W././.6XqXqX8XR.(./.T.D.Z.N.N.Z.Y.(.sX$X' . X X X     + O     O           : l ].;X0XI.S.D.Z.C.D.P.P.W.kXtXq.> $             O   O     @     X * #.:X<X).Y.Z.N.N.Z.D.P.!.6X4X3X8XkX0X/.(.Y.Y.P.D.N.b.n.n.n.n.n.N.n.n.",
(char*)"n.n.n.n.n.n.n.n.N.v.N.Z.m.P./.7XDX=Xg.1.o.[ O.-.].%XBXsX(.P.D.Z.Y.8XNX2.;   *       O O         O     . . : -.tX8X(.Y.D.N.b.N.N.N.B.Z.P.A./.fX:X+.; o       O O     X     X   X     h `.SXqXY.P.L.!./.8XrX%Xt.=.} [  .5.d.:XaXfX/.P.N.n.n.n.n.N.n.n.n.",
(char*)"n.n.n.N.n.n.n.n.n.N.N.Z.U.0XeX].` h . . . . . . & i | s.,XdX6X6XAXf._ . . X           O O O       X   X } +XkX(.P.D.N.N.N.n.n.n.n.n.n.N.Z.D.L.^.uXk.A . X                             $ [ %XAX1XsXkX&X8._ : . . o   . o o h $.[.ZX6XP.M.b.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.N.n.n.n.Z.S.I.dXOX` & .   . .   .   . . . i h ^ r.cXnX*.g . .       X   X   O 3 O O     . 2 5.iX0XT.D.N.N.n.n.n.n.n.n.n.n.n.n.n.N.N.S.U.9X*X#.$ . . .                       .   j u.PXvX-.c h > X .     .       . & $ O.*X0XF.N.c.N.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.b.D.K.8Xf.> . .         + + % , ; . ; g i h l h .     +               O O   .   $ v $XFXW.L.x.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.M.P.5XSXi.i . . .   +   O     X           . $ j h h f > o o , s H S S 4 + .   . & c H.6XL.Z.Z.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.M.N.K.fX{.: . . .                   , ; O $ p :                       O O   o   ; @.tXkX(.Y.Z.Z.b.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.M.Z.S.I.kX&X[ &       O 3 3             O . .   : ; ; * ; , #       O O         . . x OX9XU.S.Z.N.N.N.",
(char*)"n.n.n.n.n.n.b.N.P.0Xh.> & . .                   .     . % .   .         O           O . . X h g.hX(.!.T.F.n.n.n.n.n.n.n.n.n.N.n.N.b.n.n.n.n.N.n.n.M.B.D.A.0XSX1.: . .   O O O       .             X o         O   O             + . . j *X0XS.C.Z.N.n.",
(char*)"N.N.n.n.n.n.n.D.(.J.i & O O               O         O X   O .         O O         .   . . _ -X2X!.D.D.Z.N.n.v.n.n.n.n.N.N.n.n.n.n.B.n.n.n.N.v.n.n.n.N.N.D.Y./.7Xf.x . . O +   .         O O     .                               O O . . v eX6XF.B.N.n.",
(char*)"N.n.n.n.n.n.N.P.4X@.. . + 3                     O                 X                 . . =.*X0XP.Z.N.b.n.n.n.n.n.n.n.B.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.Z.C.B.Y.fX-X^ . & .         O O                                         O + O   o 6.^.P.N.n.n.",
(char*)"N.n.N.B.n.N.Z.(.rXl $     O               O O O                           X O     o > w.gXW.L.D.n.N.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.b.n.N.M.L.0XwX=.& .         O O O                                   O O     O   o @.E.S.N.n.n.",
(char*)"n.n.N.N.n.N.Z.(.rXh . .                       O   O           O O O               x h.kXI.P.Z.b.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.M.P.6XZXw.: . .       O O                                           O   . [ 3XP.N.n.n.",
(char*)"n.n.B.n.n.N.Z.T.BX^ & .                                       O O O O     X   * _ ,XfXI.P.m.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.Z.Y.(.0Xd.h .   @   O O                                           O   . @.5XD.N.n.N.",
(char*)"n.n.n.n.n.n.N.T.sXo.. .   O                                     3       *   * *.,X0XT.F.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.B.D.A.0XzX_     X                                   O             o . k.^.D.Z.n.N.",
(char*)"n.N.n.N.n.N.N.D.0X+Xi . O     .                   O O             4   X   ; r.CX0XK.Z.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.N.v.N.Z.L.9XNX*.                            O   O       O     5 O O   x wX!.M.N.n.v.",
(char*)"n.n.B.n.n.n.N.Z.Y.<X| $ . O       O                 O O                 X >.JXdXK.Z.N.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.v.D.U.dXPX( X .                         O O     O       O     ; 7.3XU.N.n.n.n.",
(char*)"n.n.n.n.n.N.n.N.D./.@Xi . .   .   O                                 .   . _.FX!.D.N.n.v.N.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.M.M.!.DX| X         O                                   . & ` wX!.D.b.n.n.n.",
(char*)"n.n.n.n.n.n.N.n.M.P.dXs.i . . . O       O                               &  XsXY.b.n.n.N.n.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.v.n.N.D.9X5.$       O   O   O                         . . & h @X6XS.N.N.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.Z.F./.sXf.l & . . . .   O O                           . i $X0XF.Z.n.n.n.N.N.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.N.Z.n.n.v.Z.T.s.& .                           O     . . . & : ^ #X~.A.D.Z.v.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.Z.A.(.sX*X$.c & & .     O                     X   . . v MX!.Z.n.v.n.n.Z.N.v.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.v.N.n.n.N.Z.Y.#X& . .                             . . . > l 8.yXW.P.D.b.N.n.n.v.n.",
(char*)"n.n.N.N.N.n.n.n.N.N.Z.Z.P.!.sXZX#Xj.g._.;.X O                         . &.dXY.N.n.n.n.n.N.N.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.N.N.D.1X^ . .     X                   . <.|.g.+X>X7X8X!.D.N.N.n.B.n.v.n.n.",
(char*)"n.N.N.N.n.n.n.n.n.N.n.n.b.D.Y.Q.Y.6XCXPXx                             2 +XW.P.M.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.n.N.Z.0Xy.. &                         o >.PXgX0XL.P.P.D.N.n.N.n.n.n.n.n.N.",
(char*)"n.n.n.N.N.n.n.n.n.n.n.b.b.N.N.D.C.^.ZX}.o                       @     c iX!.Z.N.N.n.n.b.n.n.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.N.D.(.=Xi .   +                       k cXdX/.A.Z.N.N.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.v.N.n.n.n.n.n.n.n.n.n.n.n.n.D.U.uX+.X   O               O   O . . g.9XA.D.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.D.T.gX#.$   O O                 O . . '.kXY.D.n.n.n.n.n.n.n.n.v.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.N.n.N.n.n.N.K.AX_                       O .   c tX6XD.Z.n.n.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.N.B.Y.6X+Xi . .           O       . . $ %.0XA.N.n.n.n.n.n.n.n.n.N.v.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.N.Y.kXv . X   X       .         . : s.3X!.D.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.N.N.n.Z.T.8X@.. .         O O           o @.8XD.b.n.n.n.n.n.n.n.n.N.n.n.n.",
(char*)"n.N.n.n.n.n.n.n.n.n.n.n.n.n.N.N.Z.Y.7X+.o                     o > 5.4XY.P.c.N.n.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.N.Z.!.yX .% .         O O         & i.0XD.v.n.n.n.n.n.n.n.N.N.N.n.N.",
(char*)"n.n.v.n.n.n.n.n.n.n.n.n.n.N.n.B.N.F.fXOX:   *           . . ; f s.fXY.F.B.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.F./.rX1.i .                 $ l NX/.Z.Z.n.n.n.n.n.n.n.n.B.N.N.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.D.T.7Xe.h . o . .   . & ^ e.tX^.D.Z.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.Z.P.!.W.,X%.^ $   .     X * h z.fX).D.N.N.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.S./.2Xs.+.g : h ` q..XwX8X!.Z.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.Z.Z.D.T.0X#Xf.-.^ g i x %.@X0XU.D.Z.v.N.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.Z.P.Q.3X>X,XtXiXaX(.(.Y.D.Z.N.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.Z.D.L.!.6X9XeXwX,X>XE.U.S.N.N.n.n.v.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.b.n.N.D.S.U.U.Y.Y.P.D.Z.Z.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.n.n.n.n.B.N.N.M.N.S.S.L.Y.U.P.S.M.b.b.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.N.n.n.b.b.Z.M.N.Z.N.b.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.b.N.N.B.M.M.M.b.n.N.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.n.n.n.n.b.b.b.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.v.n.n.n.n.n.b.b.b.n.n.n.n.v.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.B.n.N.n.v.n.N.n.n.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.v.n.N.B.Z.N.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.",
(char*)"n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.n.n.n.n.N.n.n.N.N.N.N.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.N.N.N.B.Z.B.Z.N.n.n.v.n.n.n.n.n.n.n.n.n.n.n.n."
};

#endif
